### ISSUE TITLE
Not working my svgoConfign in webpack

### ISSUE THREAD

**Issue by yura-master-web** [gammacommunications/vue-svg-loader-2#25]
file **index.js**

```
svgoConfig = {...svgoConfig, ...defaultConfig};
```
It will not work to merge 2 objects, it can leave one svgoConfig . And by default defaultConfig, transfer to the settings in webpack ?

```

module.exports = function vueSvgLoader(svg) {
  let { svgo: svgoConfig } = this.getOptions() || {};

  // merge svgoConfig with defaultConfig in order to force inlining <style> tags
  // svgoConfig = {...svgoConfig, ...defaultConfig}; // -> comment out

  let optimized;
  optimized = optimize(svg, {
    path: this.resourcePath,
    ...svgoConfig
  });

**Comment by ndrscodes** [comment]
whoopsies, sorry for getting back to you this late, we've been very busy lately. 

Could you describe your problem a bit more? Which node version are you currently using?

**Comment by ndrscodes** [comment]
fixed in https://github.com/gammacommunications/vue-svg-loader-2/releases/tag/0.17.0-beta.5
